### ISSUE TITLE
CurlyCloze with Cloze Hide All note

### ISSUE THREAD

**Issue by ddfonseca** [Pseudonium/Obsidian_to_Anki#55] opened 2020-09-20 15:43 UTC
It's me again 👍
I use CurlyCloze with custom regex without problem, on config I put:
`Cloze = ^T: ((?:[^\n][\n]?)+)\n+E: ((?:[^\n][\n]?)+)`
And 
`CurlyCloze = True`

So if I have a note like this:

T: My name is {David}.
E: (nothing)

Works fine!
But now I tried to put with Cloze Hide All and didn't work.  Config for Cloze Hide All:
`Cloze (Hide all) = ^T: ((?:[^\n][\n]?)+)\n+E: ((?:[^\n][\n]?)+)\n+H: ((?:[^\n][\n]?)+)`

Then, if I have a note like this:

T: First question? 
{Answer1}
Second question?
{Answer2}
Third question?
{Answer3}
E:  (nothing)
H: yes

I expected the script to create a cloze hide all note with {{c1::}}, {{c2::}} and {{c3::}}, but only translate to {Answer1} {Answer2}, without even with {Answer3} (I don't know why). 

So, is it possible to use CurlyCloze with other type of note beyond Cloze?

Thanks

**Comment by Pseudonium** [comment] 2020-09-20 15:49
Ok, so just doing some testing - it worked fine with CurlyCloze turned on, didn't work with CurlyCloze turned off.

**Comment by Pseudonium** [comment] 2020-09-20 15:50
And I got your behaviour when CurlyCloze was turned off

**Comment by ddfonseca** [comment] 2020-09-20 15:51
Hmm, I think I need to update the script, I'll try again here

**Comment by ddfonseca** [comment] 2020-09-20 15:58
Same thing. CurlyCloze turned on and didn't create the {{c1}} {{c2}} and {{c3}} on Cloze Hide All. But it works on normal Cloze.

**Comment by ddfonseca** [comment] 2020-09-20 15:58
![image](https://user-images.githubusercontent.com/9698814/93715660-01ced680-fb41-11ea-83d0-3cac0676c66c.png)

**Comment by Pseudonium** [comment] 2020-09-20 15:59
That's strange - I tested your regexp on Cloze, with the same input, and it worked fine.
Could you send me the template for Cloze Hide All?

**Comment by Pseudonium** [comment] 2020-09-20 16:01
Hmm, I have an idea of what might be causing the bug, though not sure why CurlyCloze isn't functioning properly...

**Comment by ddfonseca** [comment] 2020-09-20 16:01
Yeah, on Cloze works fine, but I'd lke to use Cloze Hide All. It's a plugin/note type, you can download it here: https://ankiweb.net/shared/info/1709973686

**Comment by Pseudonium** [comment] 2020-09-20 16:03
[test.txt](https://github.com/Pseudonium/Obsidian_to_Anki/files/5252027/test.txt)

Okay, try downloading that, changing it to a .py file, and running it. See what the output is on the command-line/GUI

**Comment by ddfonseca** [comment] 2020-09-20 16:04
![image](https://user-images.githubusercontent.com/9698814/93715771-d1d40300-fb41-11ea-93b0-304024c965cc.png)

**Comment by Pseudonium** [comment] 2020-09-20 16:07
Ah whoops, wrong file!
[test.txt](https://github.com/Pseudonium/Obsidian_to_Anki/files/5252033/test.txt)

Try that.

**Comment by ddfonseca** [comment] 2020-09-20 16:10
Strange output

![image](https://user-images.githubusercontent.com/9698814/93715917-a867a700-fb42-11ea-94d7-30f8a44c371c.png)

**Comment by Pseudonium** [comment] 2020-09-20 16:11
Ah wait I just figured it out

**Comment by Pseudonium** [comment] 2020-09-20 16:12
I just remembered that I hard-coded CurlyCloze to only work on the 'Cloze' note type, so that it doesn't do anything on other note types

**Comment by Pseudonium** [comment] 2020-09-20 16:13
So, there are two separate issues here. One is with the weird exclusion of Answer3, which I can fix in a small update (it's a feature of the markdown parser actually, but causes unexpected behaviour here).

**Comment by Pseudonium** [comment] 2020-09-20 16:13
The other issue is not being able to specify other note types as being a 'Cloze' note type. That I can fix with a small update to the config file, adding a new section to mark certain note types as 'Cloze' or not.

**Comment by Pseudonium** [comment] 2020-09-20 16:14
This should be fixed in next update (probably 2.7.1 rather than 2.8, since it's a bugfix)

**Comment by ddfonseca** [comment] 2020-09-20 16:16
Ok!! Thank you! ;)

Just a note: Cloze Hide All is better for the memorizatio, because they hide other clozes. Besides that, you can create a few simple questions on the same card! Try use that ;)

**Comment by Pseudonium** [comment] 2020-09-21 10:24
Fixed in v2.8.0. You can now also select note types to be interpreted as a Cloze type, and there are more options for CurlyCloze. Hope you find it useful!

**Closed by Pseudonium** 2020-09-21 10:24 UTC
Labels: bug
