### ISSUE TITLE
Mark notes or folders that should be ignored

### ISSUE THREAD

**Issue by leonausp** [Pseudonium/Obsidian_to_Anki#300] opened 2021-11-17 21:27 UTC
Hello
I am currently using the Header paragraph style to generate flashcards and it works quite good with my notes. The only problem I have is that it automatically applies to all the files in my vault. I have some Folders and some notes (like MOCs) that don't need to be converted to flashcards and just generate spam. Is it possible to ignore those somehow? Could we maybe include something like Target Deck: Exclude?
I mean I could just make a Trash Deck and direct all those files there, but it's kind of ugly in my opinion. My problem actually applies to all styles where you don't specify that you are making a flashcard (for example by putting "#flashcard", but you just let it do by itself.
Thanks

**Comment by hrmck** [comment] 2021-12-16 12:01
Have you checked issue #183 before? Yours seems to be a duplicate of that issue.

**Comment by hektormisplon** [comment] 2021-12-29 14:59
#289 is an open PR solving a similar issue.

**Comment by niposch** [comment] 2022-02-14 18:33
Hi, 

I added the option to ignore files or folders in the settings, because I personally need this feature.
Been using this feature for a while now and it seems to work as it is intended.
You can download the version of the plugin from here => https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1
You have to manually install it.
I am not as experienced with developing obsidian plugins as the original author, so I would advise anyone using the modified version to make a backup of their vault, just to be on the safe side.

**Comment by Nadir-Echo** [comment] 2022-05-09 08:30
> 你好
> 
> 我在设置中添加了忽略文件或文件夹的选项，因为我个人需要此功能。现在已经使用此功能一段时间了，它似乎可以按预期工作。您可以从此处下载插件的版本=>https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1 您必须手动安装它。我不像原作者那样在开发黑曜石插件方面经验丰富，所以我建议任何使用修改后版本的人备份他们的保险库，只是为了安全起见。

Thanks for your work, I have a question, what should be written in the file setting? Absolute path like this?
![image](https://user-images.githubusercontent.com/86950349/167371129-b9d652d9-5cc2-4e62-bb93-da30fb5ca41c.png)

**Comment by niposch** [comment] 2022-05-10 15:02
You have to insert relative paths. They are relative to the root directory of your vault.
This is so that you can use your vault on different computers.
The paths can contain wildcards. (Similar to how they work in gitignore files)
![image](https://user-images.githubusercontent.com/45246069/167659649-d7fe0041-02f9-4c6f-9d01-70ee52a4b15e.png)

**Comment by Nadir-Echo** [comment] 2022-05-11 05:04
> You have to insert relative paths. They are relative to the root directory of your vault. This is so that you can use your vault on different computers. The paths can contain wildcards. (Similar to how they work in gitignore files)
> 
> ![image](https://user-images.githubusercontent.com/45246069/167659649-d7fe0041-02f9-4c6f-9d01-70ee52a4b15e.png)

Thanks,I sucessed it for your advice!

**Closed** 2024-01-24 03:04 UTC
