### ISSUE TITLE
'utf-8' error

### ISSUE THREAD

**Issue by raphaelhuleux** [Pseudonium/Obsidian_to_Anki#100] opened 2020-11-26 08:52 UTC
Hello, 

When I try to update my notes to Anki, I get this new error. I'm not sure what causes it, I checked the titles of my notes and they don't have anything too weird. 

Regards,

```
Traceback (most recent call last):
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1561, in <module>
    main()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 187, in main
    App()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 880, in __init__
    Directory(
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1430, in __init__
    [
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1431, in <listcomp>
    self.file_class(entry.path)
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1109, in __init__
    self.file = f.read()
  File "/Users/raphaelhuleux/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 440: invalid start byte
```

**Comment by Pseudonium** [comment] 2020-12-05 22:24
Should hopefully be fixed in the newest release! Many people have been reporting this issue. Do let me know if it persists though.

**Comment by tedblizzard100** [comment] 2020-12-07 06:35
@Pseudonium 
Seems there might still be an issue. but happy to apply any advice you have.
Thank you for your work on this.

Traceback (most recent call last):
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1707, in <module>
    main()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 206, in main
    App()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 897, in __init__
    Directory(root, regex=args.regex)
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1578, in __init__
    for entry in it
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1581, in <listcomp>
    )[1] in App.SUPPORTED_EXTS
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1173, in __init__
    self.file = f.read()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 83: invalid start byte

**Comment by Pseudonium** [comment] 2020-12-07 07:45
Right, could you send me the problematic file?

**Comment by tedblizzard100** [comment] 2020-12-07 13:04
Writing Reference ID.md attached.
...
Identified target deck for .\Writing Reference ID.md as Default
Traceback (most recent call last):
...


[Writing Reference ID.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5652782/Writing.Reference.ID.zip)

**Comment by Pseudonium** [comment] 2020-12-07 13:11
Strange, the version of the script I'm running doesn't encounter an error when reading this file...

**Comment by tedblizzard100** [comment] 2020-12-07 23:58
Yes, very strange.  individual files process but it is when I run the entire directory that the error happens.  If there is anything else, I can do to help identify the issue, please let me know.  Thank you.

**This is what the end of the process looks like:**
Identified target deck for .\Wordie Test.md as Default
Identified target deck for .\Workbench.md as Default
Identified target deck for .\Writing Reference ID.md as Default
Traceback (most recent call last):
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1707, in <module>
    main()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 206, in main
    App()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 906, in __init__
    os.getcwd(), regex=args.regex
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1578, in __init__
    for entry in it
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1581, in <listcomp>
    )[1] in App.SUPPORTED_EXTS
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1173, in __init__
    self.file = f.read()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 83: invalid start byte

**Comment by tedblizzard100** [comment] 2020-12-08 00:16
I also see that when I process individual files I get Anki cards and everything works.  But when I process the directory, I don't get any cards inserted into Anki and no id's in Obsidian.

**Comment by Pseudonium** [comment] 2020-12-08 09:07
That's very strange indeed that individual files process but the directory doesn't. Under the hood, neither should be that different - both instantiate the same file in the same way!

**Comment by Pseudonium** [comment] 2020-12-08 09:11
And I still can't reproduce the error here, which makes it difficult to debug!

**Comment by tedblizzard100** [comment] 2020-12-08 12:54
This a screen cam to show you what it looks like: https://www.loom.com/share/85788bbbf82343debe46080cc7a7d922
Below is the error and I attached the INI in case I did something wrong in the config.

[obsidian_to_anki_config.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5659353/obsidian_to_anki_config.zip)


Attempting to connect to Anki...
Connected!
Loading configuration file...
Loaded successfully!
Traceback (most recent call last):
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1748, in <module>
    main()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 217, in main
    App()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 909, in __init__
    Directory(root, regex=args.regex)
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1604, in __init__
    for entry in it
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1607, in <listcomp>
    )[1] in App.SUPPORTED_EXTS
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1192, in __init__
    self.file = f.read()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 83: invalid start byte

**Comment by Pseudonium** [comment] 2020-12-11 15:13
One suggestion - if you use the new Obsidian plugin version of the script, this error probably won't occur? Since Obsidian takes care of reading the file.

**Comment by tedblizzard100** [comment] 2020-12-13 06:41
I changed to the plugin and refreshed all the code.  The individual files work fine but the folder still giving me a problem.  

Do you have any suggestions?  Thank you.

Attempting to connect to Anki...
Connected!
Loading configuration file...
Loaded successfully!
Traceback (most recent call last):
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1778, in <module>
    main()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 217, in main
    App()
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 936, in __init__
    os.getcwd(), regex=args.regex
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1630, in __init__
    for entry in it
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1633, in <listcomp>
    )[1] in App.SUPPORTED_EXTS
  File "C:\Users\tedbl\OneDrive\Documents\B_Brain_V1\obsidian_to_anki.py", line 1210, in __init__
    self.file = f.read()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 83: invalid start byte

**Comment by Pseudonium** [comment] 2020-12-13 10:53
Oh, by “Obsidian plugin”, I mean Obsidian_to_Anki is also a community plugin! You should be able to install it just from Obsidian, no python required.

**Comment by tedblizzard100** [comment] 2020-12-13 13:30
Yes, I installed the plugin from Obsidian.  Perhaps the documentation in the plugin is not clear about how to perform the sync between Obsidian to Anki.  It seems like the document requires the users to run the external Obsidian_to_Anki.py on the command line.  Is that correct or is there a control sync inside Obsidian that the plugin provides?

**Comment by Pseudonium** [comment] 2020-12-13 13:53
Look for an Anki icon on your ribbon - the place where ‘Open graph view’ and other buttons are.

**Comment by tedblizzard100** [comment] 2020-12-13 14:45
Yes, thank you.  I see that.  When I process the library, it is not building the cards or processing the MD files.  I am guessing I messed up the setup in some way.  At this point, I am just starting with the basic cards and the RemNote format. But it is not adding the cards to Anki. 

![Snag_348edc5](https://user-images.githubusercontent.com/145061/102015108-20cdb500-3d8c-11eb-936e-db8429fbc374.png)
![Snag_349c2e7](https://user-images.githubusercontent.com/145061/102015120-40fd7400-3d8c-11eb-822f-5c82220ea6c0.png)

**Comment by Pseudonium** [comment] 2020-12-13 14:46
Hmm, not even any console logs? You might want to try clearing the caches.

**Comment by tedblizzard100** [comment] 2020-12-13 15:31
Thank you.  Caches cleared and now itis working with the basic RemNote format.  This is a game-changer for the way I take notes.

Now, I am on to testing the cloze, images, and audio.

Thank you!

**Closed** 2020-12-13 16:05 UTC
Labels: bug
