### ISSUE TITLE
Is it possible to ignore a folder?

### ISSUE THREAD

**Issue by datavistics** [Pseudonium/Obsidian_to_Anki#302] opened 2021-11-28 05:06 UTC
I have a template folder to create a card, but it is being assigned a card and id when I use it to create a new card.

**Comment by hrmck** [comment] 2021-12-16 12:01
Have you checked issue #183 before? Yours seems to be a duplicate of that issue.

**Comment by datavistics** [comment] 2021-12-19 04:44
Yes it is, thanks @hrmck :)

**Closed** 2021-12-19 04:44 UTC
