### ISSUE TITLE
Target Deck doesn't work if the Deck is not already created. Earlier it used to create the deck (SCRIPT mode).

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#147] opened 2020-12-14 11:27 UTC
IF the deck mentioned in TARGET DECK line doesn't exist in ANKI, plugin won't create cards! or randomly creates some cards in default deck. That was my issue. I didn't see any such issue anywhere on the page nor any warnings or directions in the Wiki.

Please point me what should I do. I haven't been able to set up the thing smoothly.
Problems I am facing in this regard are:

- Target Deck not working if deck doesn't exist
- File Tags not working is tag doesn't exist.

![image](https://user-images.githubusercontent.com/68785729/102076863-693daf00-3e2e-11eb-9ab7-7c251db13f6d.png)

**Comment by dummifiedme** [comment] 2020-12-14 12:03
EDIT: I found the specific error.
If the top level deck is created (say A) in Anki, then subsequent cascaded deck (A::B::C) are being created through script automatically.
I don't know if it was intended or its a bug. Either way, it could be fixed or added to Wiki as an instruction. Since, first deck to be created manually might actually be a good practice to avoid creating wrong typo-ed decks.

**Comment by Pseudonium** [comment] 2020-12-14 12:23
According to AnkiConnect docs, adding notes into a deck that doesn't exist doesn't work. However, when changing the deck of existing notes, AnkiConnect creates the deck automatically if it doesn't already exist.

**Comment by Pseudonium** [comment] 2020-12-14 12:23
I still can't reproduce your error with tags.

**Comment by dummifiedme** [comment] 2020-12-14 13:12
The error with Tags were resolved. All the errors were linked to this error itself. As I said here https://github.com/Pseudonium/Obsidian_to_Anki/issues/148#issuecomment-744382265, is code fails, all else fails - the ID generation, the Tagging, the media etc. The loop kinda should be one note based, and not all notes, then tags, then media, then IDs.

I hope you are getting what I am trying to say.

**Comment by Pseudonium** [comment] 2020-12-14 15:13
Trust me, you don't want the loop to be single-note based - this is how the script was in its very early days, and it was **much slower** than it is currently. What I have done is implement proper error handling and logging, which will mean that IDs get written etc even if there are errors. Expect this soon.

**Comment by Pseudonium** [comment] 2020-12-14 15:26
Fixed in 3.3.4

**Closed by Pseudonium** 2020-12-14 15:26 UTC
Labels: Obsidian Plugin, bug, pending next release

**Comment by dummifiedme** [comment] 2020-12-14 16:28
> 
> 
> Trust me, you don't want the loop to be single-note based - this is how the script was in its very early days, and it was **much slower** than it is currently. What I have done is implement proper error handling and logging, which will mean that IDs get written etc even if there are errors. Expect this soon.

Got it :) Thanks for the efforts!
